openapi: "3.0.0"
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
paths:
  /resource:
    get:
      operationId: get
      responses:
        '200':
          description: Some stuff
          content:
            application/json:    
              schema:
                type: object
                propeties:
                  - collar_type:
                      type: string
                required:
                  - collar_type
                oneOf:
                  - title: Dog
                    type: object
                    properties:
                      bark_type: 
                        type: string
                    required:
                    - bark_type
                  - title: Cat
                    type: object
                    properties:
                      meow_type:
                        type: string
                    required:
                    - meow_type
