openapi: "3.0.0"
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
paths:
  /resource:
    get:
      operationId: get
      responses:
        '200':
          description: Some stuff
          content:
            application/json:    
              schema:
                type: object
                allOf:
                  - title: Location
                    type: object
                    properties:
                      location:
                        type: string
                        example: Under the couch
                    required:
                    - location
                oneOf:
                  - title: Flavor
                    type: object
                    properties:
                      flavor:
                        type: string
                        example: Strawberry
                    required:
                    - flavor
                  - title: Toxicity
                    type: object
                    properties:
                      toxicity:
                        type: string
                        example: Extremely Poisonous
                    required:
                    - toxicity
                anyOf:
                  - title: Color
                    type: object
                    properties:
                      color: 
                        type: string
                        example: Green
                    required:
                    - color
                  - title: Shape
                    type: object
                    properties:
                      shape:
                        type: string
                        example: Rectangular
                    required:
                    - shape
